services:
  app:
    container_name: express-mysql
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 1234
      DB_PORT: 3306
      DB_NAME: mysql_express
      CHOKIDAR_USEPOLLING: "true"
    depends_on: 
      - db
    ports:
      - "9000:9000"
    volumes:
      - ./:/app
      - /app/node_modules

  db:
    container_name: mysql_db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mysql_express
    ports:
      - "3307:3306"
  

  phpmyadmin:
    container_name: phpmyadmin_container
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 1234
    ports:
      - "8080:80"


