apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin-deployment
  template:
    metadata:
      labels:
        app: phpmyadmin-deployment
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin:latest
          env:
          - name: PMA_HOST
            value: mysql-service
          - name: PMA_USER
            value: root
          - name: PMA_PASSWORD
            value: "1234"
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service 
metadata:
  name: phpmyadmin-service
spec:
  selector:
    app: phpmyadmin-deployment   
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80  
  type: NodePort